### ISSUE TITLE
Macro arguments do not support commas

### ISSUE THREAD

**Issue by jakerman999** [Kyromyr/Kyromyr.github.io#21]
I wouldn't expect bare commas to be an acceptable parameter, but escaped commas should, and commas inside of strings should probably not be read as argument separators or at least be escapable.  Use cases include a macro to check substring matches.

`#ischar(c) sub(string, charidx, 1) == '{c}'`
This macro happily resolves for a large variety of c's, but the comma will complain that the macro has an extra argument.

**Comment by d0sboots** [comment]
You can work around this particular issue by defining your macro as follows:

```#ischar(c) sub(string, charidx, 1) == {c}```

And then for most characters, pass 'a', but for comma, pass (','). (You can also wrap all characters in parenthesis at the callsite if you wish.)

This works because commas are only parsed in macros at the outermost level of parenthesis.

**Comment by jakerman999** [comment]
Playing with it a bit, wrapping arguments that contain commas in an additional pair of parenthesis is a workaround.  It isn't the most intuitive or obvious, but it is functional!
